import type { ButtonHTMLAttributes,HTMLAttributes,InputHTMLAttributes,TextareaHTMLAttributes,ReactNode } from 'react';
export type ButtonVariant='primary'|'secondary'|'tertiary'|'destructive';
export function Button({variant='primary',size='standard',loading=false,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:ButtonVariant;size?:'compact'|'standard';loading?:boolean}){return <button className={`button ${variant} ${size}`} aria-busy={loading} {...props}><span className={loading?'button-label hidden':''}>{children}</span>{loading&&<span className="spinner" aria-label="Chargement"/>}</button>}
export function IconButton({variant='rest-soft',label,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'rest-soft'|'active-solid'|'destructive';label:string}){return <button className={`icon-button ${variant}`} aria-label={label} {...props}>{children}</button>}
export function Card({variant='standard',children,onClick}:HTMLAttributes<HTMLElement>&{variant?:'standard'|'interactive'|'status'|'highlight'}){const interactive=variant==='interactive'; return <section className={`card ${variant}`} onClick={onClick} role={interactive?'button':undefined} tabIndex={interactive?0:undefined}>{children}</section>}
export function ListRow({variant,title,detail,onActivate,checked=false}: {variant:'navigation'|'selection'|'toggle'|'value'|'status';title:string;detail?:string;onActivate?:()=>void;checked?:boolean}){const actionable=['navigation','selection','toggle'].includes(variant); return <div className={`list-row ${variant}`} role={variant==='toggle'?'switch':actionable?'button':undefined} aria-checked={variant==='toggle'?checked:undefined} tabIndex={actionable?0:undefined} onClick={onActivate}><span><strong>{title}</strong>{variant==='status'&&<small>● Statut opérationnel</small>}</span><span className="row-detail">{detail}{variant==='navigation'&&<span aria-hidden>›</span>}{variant==='selection'&&checked&&<span aria-label="Sélectionné">✓</span>}{variant==='toggle'&&<span className="toggle" aria-hidden/>}</span></div>}
type FieldProps={label:string;message?:string;status?:'default'|'error'|'success';multiline?:boolean} & InputHTMLAttributes<HTMLInputElement> & TextareaHTMLAttributes<HTMLTextAreaElement>;
export function Field({label,message,status='default',multiline=false,id='field',...props}:FieldProps){const described=message?`${id}-message`:undefined; return <div className={`field ${status}`}><label htmlFor={id}>{label}</label>{multiline?<textarea id={id} aria-describedby={described} aria-invalid={status==='error'} {...props}/>:<input id={id} aria-describedby={described} aria-invalid={status==='error'} {...props}/>} {message&&<small id={described}>{status==='error'?'⚠ ':status==='success'?'✓ ':''}{message}</small>}</div>}
export function Badge({variant='neutral',children}:{variant?:'neutral'|'info'|'success'|'warning'|'danger';children:ReactNode}){return <span className={`badge ${variant}`}>{children}</span>}
export function Chip({selected=false,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{selected?:boolean}){return <button className="chip" aria-pressed={selected} {...props}>{selected&&<span aria-hidden>✓ </span>}{children}</button>}
