import { useCallback, useEffect, useMemo, useState } from 'react';
import { ProjectForm } from './components/ProjectForm';
import { createProject, updateProject, type Project, type ProjectDraft } from './domain/project';
import { parseImport, serializeExport } from './domain/transfer';
import type { ProjectRepository } from './repository/ProjectRepository';
type Route={page:'home'|'new'|'settings'|'archives'}|{page:'detail'|'edit';id:string};
const routeFromHash=():Route=>{const p=location.hash.slice(1).split('/').filter(Boolean);if(p[0]==='project'&&p[1])return{page:p[2]==='edit'?'edit':'detail',id:p[1]};if(p[0]==='new'||p[0]==='settings'||p[0]==='archives')return{page:p[0]};return{page:'home'}};
const label:Record<string,string>={idea:'Idée',active:'En cours',blocked:'Bloqué',paused:'En pause',review:'En revue',completed:'Terminé',archived:'Archivé',low:'Basse',normal:'Normale',high:'Haute',critical:'Critique',github_repo:'Dépôt GitHub',github_path:'Chemin GitHub',local_folder:'Dossier local',replit:'Replit',other:'Autre'};
const go=(path:string)=>{location.hash=path};
export default function App({repository}:{repository:ProjectRepository}){const [route,setRoute]=useState(routeFromHash),[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[online,setOnline]=useState(navigator.onLine),[update,setUpdate]=useState(false);
 const load=useCallback(async()=>{try{setProjects(await repository.list());setError('')}catch(e){setError(e instanceof Error?e.message:'Chargement impossible.')}finally{setLoading(false)}},[repository]);
 useEffect(()=>{load();const hash=()=>setRoute(routeFromHash());const on=()=>setOnline(true),off=()=>setOnline(false),hadController=Boolean(navigator.serviceWorker?.controller),changed=()=>{if(hadController)setUpdate(true)};addEventListener('hashchange',hash);addEventListener('online',on);addEventListener('offline',off);navigator.serviceWorker?.addEventListener('controllerchange',changed);return()=>{removeEventListener('hashchange',hash);removeEventListener('online',on);removeEventListener('offline',off);navigator.serviceWorker?.removeEventListener('controllerchange',changed)}},[load]);
 const saveNew=async(d:ProjectDraft)=>{const p=createProject({...d,isActive:false});await repository.save(p);if(d.isActive)await repository.setActive(p.id);await load();go(`/project/${p.id}`)};
 const saveEdit=async(p:Project,d:ProjectDraft)=>{await repository.save(updateProject(p,{...d,isActive:p.isActive}));if(d.isActive&&!p.isActive)await repository.setActive(p.id);await load();go(`/project/${p.id}`)};
 const selected='id'in route?projects.find(p=>p.id===route.id):undefined;
 return <div className="app"><header><button className="brand" onClick={()=>go('/')}>DeveloperOS</button><span className={`network ${online?'online':'offline'}`} role="status">{online?'Disponible hors connexion':'Mode hors connexion'}</span></header><main>{update&&<div className="notice">Une mise à jour sera appliquée au prochain lancement.</div>}{error&&<div className="error-panel" role="alert"><strong>Une erreur est survenue.</strong><p>{error}</p><button onClick={load}>Réessayer</button></div>}{loading?<p>Chargement…</p>:route.page==='home'?<Dashboard projects={projects} />:route.page==='new'?<Page title="Nouveau projet"><ProjectForm onSave={saveNew} onCancel={()=>history.back()}/></Page>:route.page==='settings'?<Settings projects={projects} repository={repository} reload={load}/>:route.page==='archives'?<Archives projects={projects} repository={repository} reload={load}/>:selected?(route.page==='edit'?<Page title="Modifier le projet"><ProjectForm initial={selected} onSave={d=>saveEdit(selected,d)} onCancel={()=>history.back()}/></Page>:<Detail project={selected} repository={repository} reload={load}/>):<Empty title="Projet introuvable" text="Ce projet n’existe plus dans le stockage local."/>}</main><footer><nav aria-label="Navigation principale"><button onClick={()=>go('/')} aria-current={route.page==='home'?'page':undefined}>Projets</button><button onClick={()=>go('/archives')} aria-current={route.page==='archives'?'page':undefined}>Archives</button><button onClick={()=>go('/settings')} aria-current={route.page==='settings'?'page':undefined}>Réglages</button></nav></footer></div>}
function Page({title,children}:{title:string;children:React.ReactNode}){return <section><button className="back" onClick={()=>history.back()}>← Retour</button><h1>{title}</h1>{children}</section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><h2>{title}</h2><p>{text}</p></div>}
function Card({p}:{p:Project}){return <button className="card" onClick={()=>go(`/project/${p.id}`)}><span><strong>{p.name}</strong>{p.isActive&&<em>Projet actif</em>}</span><span className="chips"><span>{label[p.status]}</span><span>{label[p.priority]}</span></span><small>{p.nextAction||'Aucune prochaine action'}</small></button>}
function Dashboard({projects}:{projects:Project[]}){const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[priority,setPriority]=useState('all');const open=projects.filter(p=>p.status!=='archived');const filtered=useMemo(()=>open.filter(p=>(p.name+' '+p.aliases.join(' ')).toLowerCase().includes(query.toLowerCase())&&(status==='all'||p.status===status)&&(priority==='all'||p.priority===priority)),[open,query,status,priority]);const active=open.find(p=>p.isActive);return <section><div className="title-row"><div><p className="eyebrow">Poste de pilotage</p><h1>Mes projets</h1></div><button onClick={()=>go('/new')}>+ Créer</button></div>{active&&<div className="active"><p>Projet actif</p><Card p={active}/></div>}<div className="filters"><label>Rechercher<input type="search" placeholder="Nom ou alias" value={query} onChange={e=>setQuery(e.target.value)}/></label><div><label>État<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous</option><option value="idea">Idée</option><option value="active">En cours</option><option value="blocked">Bloqué</option><option value="paused">En pause</option><option value="review">En revue</option><option value="completed">Terminé</option></select></label><label>Priorité<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">Toutes</option><option value="low">Basse</option><option value="normal">Normale</option><option value="high">Haute</option><option value="critical">Critique</option></select></label></div></div>{!open.length?<Empty title="Aucun projet" text="Créez votre premier projet pour commencer."/>:!filtered.length?<Empty title="Aucun résultat" text="Modifiez la recherche ou les filtres."/>:<div className="cards">{filtered.filter(p=>!p.isActive).map(p=><Card key={p.id} p={p}/>)}</div>}</section>}
function Detail({project:p,repository,reload}:{project:Project;repository:ProjectRepository;reload:()=>Promise<void>}){const action=async(type:'active'|'archive')=>{if(type==='archive'&&!confirm(`Archiver « ${p.name} » ? Le projet pourra être restauré.`))return;try{if(type==='active')await repository.setActive(p.id);else await repository.archive(p.id);await reload();go(type==='archive'?'/':`/project/${p.id}`)}catch(e){alert(e instanceof Error?e.message:'Action impossible.')}};return <Page title={p.name}><div className="detail"><div className="chips"><span>{label[p.status]}</span><span>{label[p.priority]}</span>{p.isActive&&<span>Actif</span>}</div><dl><dt>Alias</dt><dd>{p.aliases.join(', ')||'—'}</dd><dt>Prochaine action</dt><dd>{p.nextAction||'—'}</dd><dt>Source canonique</dt><dd>{label[p.canonicalSourceType]} · {p.canonicalSource||'—'}</dd><dt>Dernier état connu</dt><dd>{p.lastKnownState||'—'}</dd><dt>Créé</dt><dd>{new Date(p.createdAt).toLocaleString('fr')}</dd><dt>Modifié</dt><dd>{new Date(p.updatedAt).toLocaleString('fr')}</dd></dl><button onClick={()=>go(`/project/${p.id}/edit`)}>Modifier</button>{!p.isActive&&<button className="secondary" onClick={()=>action('active')}>Rendre actif</button>}<button className="danger" onClick={()=>action('archive')}>Archiver (sans supprimer)</button></div></Page>}
function Archives({projects,repository,reload}:{projects:Project[];repository:ProjectRepository;reload:()=>Promise<void>}){const archived=projects.filter(p=>p.status==='archived');return <Page title="Archives">{!archived.length?<Empty title="Aucune archive" text="Les projets archivés apparaîtront ici."/>:<div className="cards">{archived.map(p=><div className="archive" key={p.id}><Card p={p}/><button onClick={async()=>{await repository.restore(p.id);await reload()}}>Restaurer</button></div>)}</div>}</Page>}
function Settings({projects,repository,reload}:{projects:Project[];repository:ProjectRepository;reload:()=>Promise<void>}){const [message,setMessage]=useState('');const exportData=()=>{const blob=new Blob([serializeExport(projects)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`developeros-export-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);setMessage('Export JSON créé.')};const importData=async(file?:File)=>{if(!file)return;try{const text=await file.text();const parsed=parseImport(text);if(!confirm(`Remplacer les données locales par ${parsed.length} projet(s) validé(s) ?`))return;await repository.replaceAll(parsed);await reload();setMessage('Import terminé sans perte silencieuse.')}catch(e){setMessage(e instanceof Error?e.message:'Import impossible.')}};return <Page title="Réglages"><div className="settings"><h2>Export</h2><p>Télécharge une sauvegarde JSON versionnée complète.</p><button onClick={exportData}>Exporter les données</button><h2>Import</h2><p>L’import est validé avant une transaction atomique qui remplace les données existantes après confirmation.</p><label className="file">Choisir un export JSON<input type="file" accept="application/json,.json" onChange={e=>importData(e.target.files?.[0])}/></label>{message&&<p role="status" className="notice">{message}</p>}<h2>Application</h2><p>DeveloperOS 0.1.0 · schéma 1 · données locales uniquement.</p></div></Page>}
