import { useMemo, useState } from "react";
import { useCodex } from "../data/CodexContext"; import { useProjects } from "../data/ProjectsContext";
import { CODEX_STATUSES, validateCodexUrl, validateConversation, type CodexConversation, type CodexConversationStatus } from "../domain/codexConversation"; import { Link, useNavigate, useParams } from "../routing";
const CODEX_URL="https://chatgpt.com/codex/";
export function CodexForm(){const {id}=useParams();const {conversations,save,remove}=useCodex();const {projects}=useProjects();const nav=useNavigate();const existing=useMemo(()=>conversations.find(c=>c.id===id),[conversations,id]);
 const [name,setName]=useState(existing?.name??"");const [prompt,setPrompt]=useState(existing?.prompt??"");const [projectId,setProjectId]=useState(existing?.projectId??"");const [status,setStatus]=useState<CodexConversationStatus>(existing?.status??"draft");const [url,setUrl]=useState(existing?.conversationUrl??"");const [message,setMessage]=useState("");const [fallback,setFallback]=useState(false);
 const build=(launch=false):CodexConversation=>{const now=new Date().toISOString();const validUrl=url?validateCodexUrl(url):null;return{id:existing?.id??crypto.randomUUID(),name:name.trim(),prompt,status:launch?"ready":(validUrl&&status==="ready"?"running":status),conversationUrl:validUrl,projectId:projectId||null,createdAt:existing?.createdAt??now,updatedAt:now,launchedAt:launch?now:existing?.launchedAt??null}};
 const persist=async(launch=false)=>{const value=build(launch);const errors=validateConversation(value);if(url&&!value.conversationUrl)errors.push("Le lien doit utiliser HTTPS sur chatgpt.com.");if(errors.length){setMessage(errors.join(" "));return}await save(value);if(!launch){nav(`/codex/${value.id}`);return}try{await navigator.clipboard.writeText(value.prompt);setMessage("Prompt copié. Collez-le puis validez dans Codex.")}catch{setFallback(true);setMessage("Copie impossible. Le prompt reste enregistré : sélectionnez-le ci-dessous.")}const opened=window.open(CODEX_URL,"_blank","noopener,noreferrer");if(!opened)setMessage(m=>`${m} Ouvrez Codex avec le bouton proposé.`)};
 return <section><button className="back" onClick={()=>nav(-1)}>‹ Retour</button><h1>{existing?"Modifier":"Nouvelle conversation"}</h1>{message&&<p className={fallback?"error":"notice"} role="status">{message}</p>}<div className="form-section"><label>Nom *<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Prompt *<textarea rows={10} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>Projet associé<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Aucun</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{existing&&<><label>État<select value={status} onChange={e=>setStatus(e.target.value as CodexConversationStatus)}>{CODEX_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Lien Codex<input inputMode="url" placeholder="https://chatgpt.com/..." value={url} onChange={e=>setUrl(e.target.value)}/></label></>}</div>
 {fallback&&<div className="form-section"><label>Prompt à copier<textarea readOnly rows={8} value={prompt} onFocus={e=>e.currentTarget.select()}/></label><button onClick={()=>void navigator.clipboard.writeText(prompt).then(()=>setMessage("Prompt copié.")).catch(()=>setMessage("Sélectionnez le texte et utilisez Copier."))}>Copier à nouveau</button><a className="secondary button" href={CODEX_URL} target="_blank" rel="noopener noreferrer">Ouvrir Codex</a></div>}
 <div className="sticky-actions"><button className="secondary" onClick={()=>void persist(false)}>Enregistrer comme brouillon</button><button onClick={()=>void persist(true)}>Lancer dans Codex</button></div>{existing&&<div className="inline-actions"><button className="secondary" onClick={()=>{setStatus("archived");void save({...build(),status:"archived"}).then(()=>nav("/codex"))}}>Archiver</button><button className="danger" onClick={()=>{if(confirm("Supprimer définitivement cette conversation ?"))void remove(existing.id).then(()=>nav("/codex"))}}>Supprimer</button></div>}<p className="hint">DeveloperOS copie seulement le prompt et ouvre Codex. Vous devez le coller et le valider vous-même.</p><Link to="/codex">Retour à l’historique</Link></section>}
