import { useMemo, useRef, useState, type ChangeEvent } from "react";
import { CodexCard } from "../components/CodexCard";
import { useCodex } from "../data/CodexContext";
import { CODEX_STATUSES, makeCodexExport, parseCodexExport, type CodexConversationStatus } from "../domain/codexConversation";
import { Link } from "../routing";
export function CodexList(){
 const {conversations,loading,error,reload,merge}=useCodex(); const [q,setQ]=useState(""); const [filter,setFilter]=useState<"active"|"all"|CodexConversationStatus>("active"); const [message,setMessage]=useState(""); const file=useRef<HTMLInputElement>(null);
 const shown=useMemo(()=>conversations.filter(c=>(filter==="all"||(filter==="active"?c.status!=="archived":c.status===filter))&&`${c.name} ${c.prompt}`.toLowerCase().includes(q.trim().toLowerCase())),[conversations,q,filter]);
 const exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(makeCodexExport(conversations),null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="developeros-codex.json";a.click();URL.revokeObjectURL(url);setMessage("Export Codex téléchargé.")};
 const importData=async(e:ChangeEvent<HTMLInputElement>)=>{const selected=e.target.files?.[0];if(!selected)return;try{const values=parseCodexExport(JSON.parse(await selected.text()));if(confirm(`Fusionner ${values.length} conversation(s), sans supprimer les données locales ?`)){await merge(values);setMessage("Import fusionné.")}}catch(err){setMessage(err instanceof Error?err.message:"Import impossible.")}finally{e.target.value=""}};
 return <section><p className="eyebrow">Historique local</p><div className="module-title"><h1>Codex</h1><Link className="secondary button" to="/">Projets</Link></div>{message&&<p className="notice" role="status">{message}</p>}
 <div className="toolbar"><label className="search"><span>⌕</span><input aria-label="Rechercher les conversations" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nom ou prompt"/></label><select aria-label="Filtrer les conversations" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="active">Non archivées</option><option value="all">Toutes</option>{CODEX_STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select></div>
 <div className="inline-actions compact"><button className="secondary" onClick={exportData}>Exporter JSON</button><button className="secondary" onClick={()=>file.current?.click()}>Importer (fusion)</button><input className="sr-only" ref={file} aria-label="Importer des conversations Codex" type="file" accept="application/json,.json" onChange={e=>void importData(e)}/></div>
 {loading&&<p role="status">Chargement…</p>}{error&&<div className="error" role="alert">{error}<button onClick={()=>void reload()}>Réessayer</button></div>}{!loading&&!error&&!shown.length&&<div className="empty"><h2>Aucune conversation</h2><p>Créez une entrée, puis copiez son prompt vers Codex.</p></div>}<div className="cards">{shown.map(c=><CodexCard key={c.id} conversation={c}/>)}</div><Link className="fab" aria-label="Nouvelle conversation" to="/codex/new">＋</Link></section>
}
